name: Build

on:
  push:
    branches:
      - 'p-plus'
      - '!master'
  pull_request:
    branches:
      - 'p-plus'
      - '!master'
  workflow_dispatch:
    branches:
      - 'p-plus'
      - '!master'

permissions:
  contents: write

env:
  MAKEFLAGS: "-j4 GITVERSION=${{ github.sha }}"

jobs:

  simpl:
    name: Builder
    runs-on: ubuntu-latest
    steps:

      - name: Set up dependencies
        run: |
          sudo apt install make gcc git mtools util-linux liblzma-dev isolinux xorriso genisoimage gh
            
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: prepare Identity
        run: |
          git config set user.name "Tadej Panjtar action bot" && \
          git config set user.email "you@gmail.com"
          
      - name: Prepare
        run: |
          git branch -a && git merge origin/add-range-support-to-imgfetch-3337836681896013988 -m range-support --quiet

      - name: Build
        working-directory: src
        run: |
          make bin/ipxe.iso \
               bin/ipxe.usb \
               bin-x86_64-efi/ipxe.efi

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: skupen-paket
          if-no-files-found: error
          path: |
            src/bin/ipxe.iso
            src/bin/ipxe.usb
            src/bin-x86_64-efi/ipxe.efi

      - name: Download
        uses: actions/download-artifact@v7
        with:
          pattern: "skupen-paket"

      - name: Release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Calculating signatures ...; \
          sha256sum \
              bin/ipxe.iso \
              bin/ipxe.usb \
              bin-x86_64-efi/ipxe.efi; \
          gh release create "${{ github.ref_name }}" --draft \
              --title "Release $(date +%Y-%m-%d)" \
              bin/ipxe.iso \
              bin/ipxe.usb \
              bin-x86_64-efi/ipxe.efi
